### PR TITLE
Added Apache 2.0 License

### PR DESCRIPTION
**Pull request by limenet**
As per #58 

Let me know if you'd like me to make any changes.

### CODE REVIEW

**Comment by limenet** [comment]
I took the liberty of changing the syntax for the prompts to [the currently official syntax](https://github.com/sboudrias/Inquirer.js#installation):

```
var inquirer = require('inquirer');
inquirer.prompt([/* Pass your questions in here */]).then(function (answers) {
    // Use user feedback for... whatever!!
});
```

This way, `make-license` works perfectly on Windows.

---

I know, one PR should only be one feature, but I hope you don't mind :) Otherwise the PR to address #58 and the one to fix the syntax would conflict, that was the rationale.

**Update:** reverted syntax change due to conflict with #69

**Comment by accraze** [comment]
thanks @limenet this is great!

**Comment by limenet** [comment]
@accraze you're welcome! Sorry for the mess I created with the commits.

**Comment by accraze** [comment]
no worries @limenet  thanks for your interest in the project!

**Pull request merged**
